Fixed an error when deleting a record
Fixed an error when deleting a record if the icon field is null

TypeError: App\Models\User::deleteImage(): Argument #1 ($filePath) must be of type string, null given, called in /var/www/html/vendor/qcod/laravel-imageup/src/HasImageUploads.php on line 800 and defined in /var/www/html/vendor/qcod/laravel-imageup/src/HasImageUploads.php:64